categorical_vars = [
    "CESFAM",
    "RANGO_EDAD",
    "NIVEL_ESTUDIOS",
    "OCUPACION",
    "NACIONALIDAD",
    "PESOGANADODEPENTEDEPESOALINICIO",
    "CUANTO_DEBERIA_SUBIR",
    "ESTADO_NUTRICIONAL_AUTOREPORTADO",
    "FRUTAS_XNT",
    "AGUA_XNT",
    "SELLOS_XNT",
    "SNACK_DULCE_XNT",
    "SNACK_SALADO_XNT",
    "CHATARRA_XNT",
    "SAL_XNT",
    "BEBIDA_AZUCAR_XNT",
    "BEBIDA_ENDULZANTE_XNT",
    "FRITURAS_XNT",
    "NIVELAF",
    "EN_PREGEST",
    "COMUNA",
    "cumpleprot",
    "cumplecho",
    "cumplefibra",
    "cumplesat",
    "cumplemono",
    "cumplepoli",
    "cumplerazon36",
    "cumplefos",
    "cumplek",
    "cumplese",
    "cumplena",
    "cumplezn",
    "cumplevite",
    "cumpleca",
    "cumplecu",
    "cumplemg",
    "cumpleb12",
    "cumplefol",
    "cumplepanto",
    "cumplevitc",
    "cumplevitd",
    "cumplevita",
    "cumpletiam",
    "cumpleb2",
    "cumplenia",
    "cumpleb6",
    "interpretacion_patrones",
]


binary_vars = [
    "HIJOS",
    "PAREJA",
    "FAMILA_DIRECTA",
    "FAMILIA_PAREJA",
    "OTROS",
    "NIVEL_ESTUDIOS",
    "OCUPACION",
    "ALTERACION_ORINA",
    "CES_PREVIA",
    "OBESIDAD",
    "DG_A",
    "HTA",
    "RI",
    "PESOMATERNOINFLUYEENSALUD",
    "PREOCUPACIONPORSUBIRDEPESO",
    "ESIMPORTANTESUBIRDEPESO",
    "NECESITAAYUDANUTRICIONAL",
    "FUMA_PREVIO_EMBARAZO",
    "FUMA_ACTUALMENTE",
    "ALCOHOL_DROGAS_PREVIO",
    "ALCOHOL_DROGA_ACTUAL",
]


numerics_var = [
    "puntaje_patrones" "Calorias",
    "Hidratosg",
    "Saturadosg",
    "Monoinsatg",
    "Poliinsatg",
    "omega6g",
    "omega3g",
    "Vit.B1mg",
    "VitB2mg",
    "Niacinamg",
    "VitB6mg",
    "VitB12mg",
    "Folatosmcg",
    "Pantoténicomg",
    "VitDUI",
    "VitEmg",
    "Calciomg",
    "Magnesiomg",
    "Fosforomg",
    "Seleniomcg",
    "sodiomg",
    "Zincmg",
]


outcome = "soloegwg"
